### ISSUE TITLE
Fasta input with '.fa' extension invalid

### ISSUE THREAD

**Issue by samnooij** [MGXlab/Jaeger#1]
Thanks for making this awesome tool! I've been giving it a try on files with `.fa`, `.fna` and `.fasta` extensions and noticed that `.fa` is not recognized as a valid fasta file. It seems you have run into this issue as well, judging from this code line:
[    # if input_file.endswith('fna') or input_file.endswith('fasta') or input_file.endswith('txt') :](https://github.com/MGXlab/Jaeger/blob/756c1c9f8486f47191b0d3e166a94e63aeab47d7/bin/jaeger#L258)
Are you planning to make a new release soon and incorporate this fix?

I have managed to manually patch this by including `or input_file.endswith('.fa')` in my installation ([line 193](https://github.com/MGXlab/Jaeger/blob/74d4868b2b6edf3d2a8eda3ff7388e772f6a7a00/bin/Jaeger#L193)), but for reproducibility it would be nice if there were a release that works with my `.fa` files. 😄

By the way, for the record, I installed version 1.1.26 through conda using the following YAML (saved as `jaeger.yaml`):
```yaml
name: jaeger

dependencies:
 - jaeger-bio=1.1.26

channels:
 - conda-forge
 - bioconda
```

with
```bash
mamba env create -f jaeger.yaml
```

**Comment by Yasas1994** [comment]
Hi Sam, 
Thanks for reporting this issue. I will patch this as soon as possible.

**Comment by Yasas1994** [comment]
It is fixed now 👍🏽 

version 1.1.30 is now available on PyPi and coming soon to Bioconda
